/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMyLearningRouteImport } from './routes/_authenticated/my-learning'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses/index'
import { Route as AuthenticatedReportsFeedbackRouteImport } from './routes/_authenticated/reports/feedback'
import { Route as AuthenticatedManagerLessonProgressRouteImport } from './routes/_authenticated/manager/lesson-progress'
import { Route as AuthenticatedLessonsLessonIdRouteImport } from './routes/_authenticated/lessons/$lessonId'
import { Route as AuthenticatedCoursesIdRouteImport } from './routes/_authenticated/courses/$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTeamsRouteImport } from './routes/_authenticated/admin/teams'
import { Route as AuthenticatedManagerModulesIndexRouteImport } from './routes/_authenticated/manager/modules/index'
import { Route as AuthenticatedManagerCoursesIndexRouteImport } from './routes/_authenticated/manager/courses/index'
import { Route as AuthenticatedManagerModulesIdRouteImport } from './routes/_authenticated/manager/modules/$id'
import { Route as AuthenticatedManagerLessonsLessonIdRouteImport } from './routes/_authenticated/manager/lessons/$lessonId'
import { Route as AuthenticatedManagerCoursesIdRouteImport } from './routes/_authenticated/manager/courses/$id'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users.$id'
import { Route as AuthenticatedAdminTeamsIdRouteImport } from './routes/_authenticated/admin/teams.$id'
import { Route as AuthenticatedManagerQuizzesIdAnalyticsRouteImport } from './routes/_authenticated/manager/quizzes/$id/analytics'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyLearningRoute = AuthenticatedMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)
const AuthenticatedReportsFeedbackRoute =
  AuthenticatedReportsFeedbackRouteImport.update({
    id: '/reports/feedback',
    path: '/reports/feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerLessonProgressRoute =
  AuthenticatedManagerLessonProgressRouteImport.update({
    id: '/manager/lesson-progress',
    path: '/manager/lesson-progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsLessonIdRoute =
  AuthenticatedLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesIdRoute = AuthenticatedCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCoursesRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTeamsRoute = AuthenticatedAdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerModulesIndexRoute =
  AuthenticatedManagerModulesIndexRouteImport.update({
    id: '/manager/modules/',
    path: '/manager/modules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerCoursesIndexRoute =
  AuthenticatedManagerCoursesIndexRouteImport.update({
    id: '/manager/courses/',
    path: '/manager/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerModulesIdRoute =
  AuthenticatedManagerModulesIdRouteImport.update({
    id: '/manager/modules/$id',
    path: '/manager/modules/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerLessonsLessonIdRoute =
  AuthenticatedManagerLessonsLessonIdRouteImport.update({
    id: '/manager/lessons/$lessonId',
    path: '/manager/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerCoursesIdRoute =
  AuthenticatedManagerCoursesIdRouteImport.update({
    id: '/manager/courses/$id',
    path: '/manager/courses/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminTeamsIdRoute =
  AuthenticatedAdminTeamsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTeamsRoute,
  } as any)
const AuthenticatedManagerQuizzesIdAnalyticsRoute =
  AuthenticatedManagerQuizzesIdAnalyticsRouteImport.update({
    id: '/manager/quizzes/$id/analytics',
    path: '/manager/quizzes/$id/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/manager/lesson-progress': typeof AuthenticatedManagerLessonProgressRoute
  '/reports/feedback': typeof AuthenticatedReportsFeedbackRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/admin/teams/$id': typeof AuthenticatedAdminTeamsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/manager/courses/$id': typeof AuthenticatedManagerCoursesIdRoute
  '/manager/lessons/$lessonId': typeof AuthenticatedManagerLessonsLessonIdRoute
  '/manager/modules/$id': typeof AuthenticatedManagerModulesIdRoute
  '/manager/courses': typeof AuthenticatedManagerCoursesIndexRoute
  '/manager/modules': typeof AuthenticatedManagerModulesIndexRoute
  '/manager/quizzes/$id/analytics': typeof AuthenticatedManagerQuizzesIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/manager/lesson-progress': typeof AuthenticatedManagerLessonProgressRoute
  '/reports/feedback': typeof AuthenticatedReportsFeedbackRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/admin/teams/$id': typeof AuthenticatedAdminTeamsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/manager/courses/$id': typeof AuthenticatedManagerCoursesIdRoute
  '/manager/lessons/$lessonId': typeof AuthenticatedManagerLessonsLessonIdRoute
  '/manager/modules/$id': typeof AuthenticatedManagerModulesIdRoute
  '/manager/courses': typeof AuthenticatedManagerCoursesIndexRoute
  '/manager/modules': typeof AuthenticatedManagerModulesIndexRoute
  '/manager/quizzes/$id/analytics': typeof AuthenticatedManagerQuizzesIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/my-learning': typeof AuthenticatedMyLearningRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/teams': typeof AuthenticatedAdminTeamsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/_authenticated/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/_authenticated/manager/lesson-progress': typeof AuthenticatedManagerLessonProgressRoute
  '/_authenticated/reports/feedback': typeof AuthenticatedReportsFeedbackRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/admin/teams/$id': typeof AuthenticatedAdminTeamsIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/manager/courses/$id': typeof AuthenticatedManagerCoursesIdRoute
  '/_authenticated/manager/lessons/$lessonId': typeof AuthenticatedManagerLessonsLessonIdRoute
  '/_authenticated/manager/modules/$id': typeof AuthenticatedManagerModulesIdRoute
  '/_authenticated/manager/courses/': typeof AuthenticatedManagerCoursesIndexRoute
  '/_authenticated/manager/modules/': typeof AuthenticatedManagerModulesIndexRoute
  '/_authenticated/manager/quizzes/$id/analytics': typeof AuthenticatedManagerQuizzesIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-in'
    | '/courses'
    | '/my-learning'
    | '/settings'
    | '/'
    | '/admin/teams'
    | '/admin/users'
    | '/courses/$id'
    | '/lessons/$lessonId'
    | '/manager/lesson-progress'
    | '/reports/feedback'
    | '/courses/'
    | '/admin/teams/$id'
    | '/admin/users/$id'
    | '/manager/courses/$id'
    | '/manager/lessons/$lessonId'
    | '/manager/modules/$id'
    | '/manager/courses'
    | '/manager/modules'
    | '/manager/quizzes/$id/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-in'
    | '/my-learning'
    | '/settings'
    | '/'
    | '/admin/teams'
    | '/admin/users'
    | '/courses/$id'
    | '/lessons/$lessonId'
    | '/manager/lesson-progress'
    | '/reports/feedback'
    | '/courses'
    | '/admin/teams/$id'
    | '/admin/users/$id'
    | '/manager/courses/$id'
    | '/manager/lessons/$lessonId'
    | '/manager/modules/$id'
    | '/manager/courses'
    | '/manager/modules'
    | '/manager/quizzes/$id/analytics'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/_authenticated/courses'
    | '/_authenticated/my-learning'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/admin/teams'
    | '/_authenticated/admin/users'
    | '/_authenticated/courses/$id'
    | '/_authenticated/lessons/$lessonId'
    | '/_authenticated/manager/lesson-progress'
    | '/_authenticated/reports/feedback'
    | '/_authenticated/courses/'
    | '/_authenticated/admin/teams/$id'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/manager/courses/$id'
    | '/_authenticated/manager/lessons/$lessonId'
    | '/_authenticated/manager/modules/$id'
    | '/_authenticated/manager/courses/'
    | '/_authenticated/manager/modules/'
    | '/_authenticated/manager/quizzes/$id/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-learning': {
      id: '/_authenticated/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AuthenticatedMyLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/_authenticated/reports/feedback': {
      id: '/_authenticated/reports/feedback'
      path: '/reports/feedback'
      fullPath: '/reports/feedback'
      preLoaderRoute: typeof AuthenticatedReportsFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/lesson-progress': {
      id: '/_authenticated/manager/lesson-progress'
      path: '/manager/lesson-progress'
      fullPath: '/manager/lesson-progress'
      preLoaderRoute: typeof AuthenticatedManagerLessonProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/$lessonId': {
      id: '/_authenticated/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$id': {
      id: '/_authenticated/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AuthenticatedCoursesIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/teams': {
      id: '/_authenticated/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AuthenticatedAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/modules/': {
      id: '/_authenticated/manager/modules/'
      path: '/manager/modules'
      fullPath: '/manager/modules'
      preLoaderRoute: typeof AuthenticatedManagerModulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/courses/': {
      id: '/_authenticated/manager/courses/'
      path: '/manager/courses'
      fullPath: '/manager/courses'
      preLoaderRoute: typeof AuthenticatedManagerCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/modules/$id': {
      id: '/_authenticated/manager/modules/$id'
      path: '/manager/modules/$id'
      fullPath: '/manager/modules/$id'
      preLoaderRoute: typeof AuthenticatedManagerModulesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/lessons/$lessonId': {
      id: '/_authenticated/manager/lessons/$lessonId'
      path: '/manager/lessons/$lessonId'
      fullPath: '/manager/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedManagerLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/courses/$id': {
      id: '/_authenticated/manager/courses/$id'
      path: '/manager/courses/$id'
      fullPath: '/manager/courses/$id'
      preLoaderRoute: typeof AuthenticatedManagerCoursesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/teams/$id': {
      id: '/_authenticated/admin/teams/$id'
      path: '/$id'
      fullPath: '/admin/teams/$id'
      preLoaderRoute: typeof AuthenticatedAdminTeamsIdRouteImport
      parentRoute: typeof AuthenticatedAdminTeamsRoute
    }
    '/_authenticated/manager/quizzes/$id/analytics': {
      id: '/_authenticated/manager/quizzes/$id/analytics'
      path: '/manager/quizzes/$id/analytics'
      fullPath: '/manager/quizzes/$id/analytics'
      preLoaderRoute: typeof AuthenticatedManagerQuizzesIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesIdRoute: typeof AuthenticatedCoursesIdRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesIdRoute: AuthenticatedCoursesIdRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedAdminTeamsRouteChildren {
  AuthenticatedAdminTeamsIdRoute: typeof AuthenticatedAdminTeamsIdRoute
}

const AuthenticatedAdminTeamsRouteChildren: AuthenticatedAdminTeamsRouteChildren =
  {
    AuthenticatedAdminTeamsIdRoute: AuthenticatedAdminTeamsIdRoute,
  }

const AuthenticatedAdminTeamsRouteWithChildren =
  AuthenticatedAdminTeamsRoute._addFileChildren(
    AuthenticatedAdminTeamsRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedMyLearningRoute: typeof AuthenticatedMyLearningRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminTeamsRoute: typeof AuthenticatedAdminTeamsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedLessonsLessonIdRoute: typeof AuthenticatedLessonsLessonIdRoute
  AuthenticatedManagerLessonProgressRoute: typeof AuthenticatedManagerLessonProgressRoute
  AuthenticatedReportsFeedbackRoute: typeof AuthenticatedReportsFeedbackRoute
  AuthenticatedManagerCoursesIdRoute: typeof AuthenticatedManagerCoursesIdRoute
  AuthenticatedManagerLessonsLessonIdRoute: typeof AuthenticatedManagerLessonsLessonIdRoute
  AuthenticatedManagerModulesIdRoute: typeof AuthenticatedManagerModulesIdRoute
  AuthenticatedManagerCoursesIndexRoute: typeof AuthenticatedManagerCoursesIndexRoute
  AuthenticatedManagerModulesIndexRoute: typeof AuthenticatedManagerModulesIndexRoute
  AuthenticatedManagerQuizzesIdAnalyticsRoute: typeof AuthenticatedManagerQuizzesIdAnalyticsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedMyLearningRoute: AuthenticatedMyLearningRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminTeamsRoute: AuthenticatedAdminTeamsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedLessonsLessonIdRoute: AuthenticatedLessonsLessonIdRoute,
  AuthenticatedManagerLessonProgressRoute:
    AuthenticatedManagerLessonProgressRoute,
  AuthenticatedReportsFeedbackRoute: AuthenticatedReportsFeedbackRoute,
  AuthenticatedManagerCoursesIdRoute: AuthenticatedManagerCoursesIdRoute,
  AuthenticatedManagerLessonsLessonIdRoute:
    AuthenticatedManagerLessonsLessonIdRoute,
  AuthenticatedManagerModulesIdRoute: AuthenticatedManagerModulesIdRoute,
  AuthenticatedManagerCoursesIndexRoute: AuthenticatedManagerCoursesIndexRoute,
  AuthenticatedManagerModulesIndexRoute: AuthenticatedManagerModulesIndexRoute,
  AuthenticatedManagerQuizzesIdAnalyticsRoute:
    AuthenticatedManagerQuizzesIdAnalyticsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
